#![feature(abi_msp430_interrupt)]
#![doc = "Peripheral access API for MSP430FR2476 microcontrollers (generated using svd2rust v0.36.1 ( ))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.36.1/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_auto_cfg))]
#[allow(unused_imports)]
use generic::*;
#[doc = "Common register and bit access and modify traits"]
pub mod generic;
#[cfg(feature = "rt")]
extern "msp430-interrupt" {
    fn ECOMP0();
    fn PORT6();
    fn PORT5();
    fn PORT4();
    fn PORT3();
    fn PORT2();
    fn PORT1();
    fn ADC();
    fn EUSCI_B1();
    fn EUSCI_B0();
    fn EUSCI_A1();
    fn EUSCI_A0();
    fn WDT();
    fn RTC();
    fn TIMER0_B1();
    fn TIMER0_B0();
    fn TIMER3_A1();
    fn TIMER3_A0();
    fn TIMER2_A1();
    fn TIMER2_A0();
    fn TIMER1_A1();
    fn TIMER1_A0();
    fn TIMER0_A1();
    fn TIMER0_A0();
    fn UNMI();
    fn SYSNMI();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    _handler: unsafe extern "msp430-interrupt" fn(),
    _reserved: u16,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[link_section = ".vector_table.interrupts"]
#[no_mangle]
#[used]
pub static __INTERRUPTS: [Vector; 63] = [
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: ECOMP0 },
    Vector { _handler: PORT6 },
    Vector { _handler: PORT5 },
    Vector { _handler: PORT4 },
    Vector { _handler: PORT3 },
    Vector { _handler: PORT2 },
    Vector { _handler: PORT1 },
    Vector { _handler: ADC },
    Vector { _handler: EUSCI_B1 },
    Vector { _handler: EUSCI_B0 },
    Vector { _handler: EUSCI_A1 },
    Vector { _handler: EUSCI_A0 },
    Vector { _handler: WDT },
    Vector { _handler: RTC },
    Vector {
        _handler: TIMER0_B1,
    },
    Vector {
        _handler: TIMER0_B0,
    },
    Vector {
        _handler: TIMER3_A1,
    },
    Vector {
        _handler: TIMER3_A0,
    },
    Vector {
        _handler: TIMER2_A1,
    },
    Vector {
        _handler: TIMER2_A0,
    },
    Vector {
        _handler: TIMER1_A1,
    },
    Vector {
        _handler: TIMER1_A0,
    },
    Vector {
        _handler: TIMER0_A1,
    },
    Vector {
        _handler: TIMER0_A0,
    },
    Vector { _handler: UNMI },
    Vector { _handler: SYSNMI },
];
#[doc = r"Enumeration of all the interrupts. This enum is seldom used in application or library crates. It is present primarily for documenting the device's implemented interrupts."]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    #[doc = "19 - 0xFFCA"]
    ECOMP0 = 19,
    #[doc = "20 - 0xFFCC"]
    PORT6 = 20,
    #[doc = "21 - 0xFFCE"]
    PORT5 = 21,
    #[doc = "22 - 0xFFD0"]
    PORT4 = 22,
    #[doc = "23 - 0xFFD2"]
    PORT3 = 23,
    #[doc = "24 - 0xFFD4"]
    PORT2 = 24,
    #[doc = "25 - 0xFFD6"]
    PORT1 = 25,
    #[doc = "26 - 0xFFD8"]
    ADC = 26,
    #[doc = "27 - 0xFFDA"]
    EUSCI_B1 = 27,
    #[doc = "28 - 0xFFDC"]
    EUSCI_B0 = 28,
    #[doc = "29 - 0xFFDE"]
    EUSCI_A1 = 29,
    #[doc = "30 - 0xFFE0"]
    EUSCI_A0 = 30,
    #[doc = "31 - 0xFFE2"]
    WDT = 31,
    #[doc = "32 - 0xFFE4"]
    RTC = 32,
    #[doc = "33 - 0xFFE6"]
    TIMER0_B1 = 33,
    #[doc = "34 - 0xFFE8"]
    TIMER0_B0 = 34,
    #[doc = "35 - 0xFFEA"]
    TIMER3_A1 = 35,
    #[doc = "36 - 0xFFEC"]
    TIMER3_A0 = 36,
    #[doc = "37 - 0xFFEE"]
    TIMER2_A1 = 37,
    #[doc = "38 - 0xFFF0"]
    TIMER2_A0 = 38,
    #[doc = "39 - 0xFFF2"]
    TIMER1_A1 = 39,
    #[doc = "40 - 0xFFF4"]
    TIMER1_A0 = 40,
    #[doc = "41 - 0xFFF6"]
    TIMER0_A1 = 41,
    #[doc = "42 - 0xFFF8"]
    TIMER0_A0 = 42,
    #[doc = "43 - 0xFFFA"]
    UNMI = 43,
    #[doc = "44 - 0xFFFC"]
    SYSNMI = 44,
}
#[doc = "P1"]
pub type P1 = crate::Periph<p1::RegisterBlock, 0x0200>;
impl core::fmt::Debug for P1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("P1").finish()
    }
}
#[doc = "P1"]
pub mod p1;
#[doc = "P2"]
pub type P2 = crate::Periph<p2::RegisterBlock, 0x0200>;
impl core::fmt::Debug for P2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("P2").finish()
    }
}
#[doc = "P2"]
pub mod p2;
#[doc = "P3"]
pub type P3 = crate::Periph<p3::RegisterBlock, 0x0220>;
impl core::fmt::Debug for P3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("P3").finish()
    }
}
#[doc = "P3"]
pub mod p3;
#[doc = "P4"]
pub type P4 = crate::Periph<p4::RegisterBlock, 0x0220>;
impl core::fmt::Debug for P4 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("P4").finish()
    }
}
#[doc = "P4"]
pub mod p4;
#[doc = "P5"]
pub type P5 = crate::Periph<p5::RegisterBlock, 0x0240>;
impl core::fmt::Debug for P5 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("P5").finish()
    }
}
#[doc = "P5"]
pub mod p5;
#[doc = "P6"]
pub type P6 = crate::Periph<p6::RegisterBlock, 0x0240>;
impl core::fmt::Debug for P6 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("P6").finish()
    }
}
#[doc = "P6"]
pub mod p6;
#[doc = "SFR"]
pub type Sfr = crate::Periph<sfr::RegisterBlock, 0x0100>;
impl core::fmt::Debug for Sfr {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sfr").finish()
    }
}
#[doc = "SFR"]
pub mod sfr;
#[doc = "PMM"]
pub type Pmm = crate::Periph<pmm::RegisterBlock, 0x0120>;
impl core::fmt::Debug for Pmm {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pmm").finish()
    }
}
#[doc = "PMM"]
pub mod pmm;
#[doc = "SYS"]
pub type Sys = crate::Periph<sys::RegisterBlock, 0x0140>;
impl core::fmt::Debug for Sys {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sys").finish()
    }
}
#[doc = "SYS"]
pub mod sys;
#[doc = "CS"]
pub type Cs = crate::Periph<cs::RegisterBlock, 0x0180>;
impl core::fmt::Debug for Cs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Cs").finish()
    }
}
#[doc = "CS"]
pub mod cs;
#[doc = "FRCTL"]
pub type Frctl = crate::Periph<frctl::RegisterBlock, 0x01a0>;
impl core::fmt::Debug for Frctl {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Frctl").finish()
    }
}
#[doc = "FRCTL"]
pub mod frctl;
#[doc = "CRC"]
pub type Crc = crate::Periph<crc::RegisterBlock, 0x01c0>;
impl core::fmt::Debug for Crc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Crc").finish()
    }
}
#[doc = "CRC"]
pub mod crc;
#[doc = "WDT_A"]
pub type WdtA = crate::Periph<wdt_a::RegisterBlock, 0x01cc>;
impl core::fmt::Debug for WdtA {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("WdtA").finish()
    }
}
#[doc = "WDT_A"]
pub mod wdt_a;
#[doc = "RTC"]
pub type Rtc = crate::Periph<rtc::RegisterBlock, 0x0300>;
impl core::fmt::Debug for Rtc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rtc").finish()
    }
}
#[doc = "RTC"]
pub mod rtc;
#[doc = "PJ"]
pub type Pj = crate::Periph<pj::RegisterBlock, 0x0320>;
impl core::fmt::Debug for Pj {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pj").finish()
    }
}
#[doc = "PJ"]
pub mod pj;
#[doc = "TA0"]
pub type Ta0 = crate::Periph<ta0::RegisterBlock, 0x0380>;
impl core::fmt::Debug for Ta0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ta0").finish()
    }
}
#[doc = "TA0"]
pub mod ta0;
#[doc = "TA1"]
pub type Ta1 = crate::Periph<ta1::RegisterBlock, 0x03c0>;
impl core::fmt::Debug for Ta1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ta1").finish()
    }
}
#[doc = "TA1"]
pub mod ta1;
#[doc = "TA2"]
pub type Ta2 = crate::Periph<ta2::RegisterBlock, 0x0400>;
impl core::fmt::Debug for Ta2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ta2").finish()
    }
}
#[doc = "TA2"]
pub mod ta2;
#[doc = "TA3"]
pub type Ta3 = crate::Periph<ta3::RegisterBlock, 0x0440>;
impl core::fmt::Debug for Ta3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ta3").finish()
    }
}
#[doc = "TA3"]
pub mod ta3;
#[doc = "TB0"]
pub type Tb0 = crate::Periph<tb0::RegisterBlock, 0x0480>;
impl core::fmt::Debug for Tb0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tb0").finish()
    }
}
#[doc = "TB0"]
pub mod tb0;
#[doc = "MPY32"]
pub type Mpy32 = crate::Periph<mpy32::RegisterBlock, 0x04c0>;
impl core::fmt::Debug for Mpy32 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Mpy32").finish()
    }
}
#[doc = "MPY32"]
pub mod mpy32;
#[doc = "eUSCI_A0"]
pub type EUsciA0 = crate::Periph<e_usci_a0::RegisterBlock, 0x0500>;
impl core::fmt::Debug for EUsciA0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("EUsciA0").finish()
    }
}
#[doc = "eUSCI_A0"]
pub mod e_usci_a0;
#[doc = "eUSCI_A1"]
pub type EUsciA1 = crate::Periph<e_usci_a1::RegisterBlock, 0x0520>;
impl core::fmt::Debug for EUsciA1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("EUsciA1").finish()
    }
}
#[doc = "eUSCI_A1"]
pub mod e_usci_a1;
#[doc = "eUSCI_B0"]
pub type EUsciB0 = crate::Periph<e_usci_b0::RegisterBlock, 0x0540>;
impl core::fmt::Debug for EUsciB0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("EUsciB0").finish()
    }
}
#[doc = "eUSCI_B0"]
pub mod e_usci_b0;
#[doc = "eUSCI_B1"]
pub type EUsciB1 = crate::Periph<e_usci_b1::RegisterBlock, 0x0580>;
impl core::fmt::Debug for EUsciB1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("EUsciB1").finish()
    }
}
#[doc = "eUSCI_B1"]
pub mod e_usci_b1;
#[doc = "BKMEM"]
pub type Bkmem = crate::Periph<bkmem::RegisterBlock, 0x0660>;
impl core::fmt::Debug for Bkmem {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Bkmem").finish()
    }
}
#[doc = "BKMEM"]
pub mod bkmem;
#[doc = "ADC"]
pub type Adc = crate::Periph<adc::RegisterBlock, 0x0700>;
impl core::fmt::Debug for Adc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Adc").finish()
    }
}
#[doc = "ADC"]
pub mod adc;
#[doc = "eCOMP0"]
pub type EComp0 = crate::Periph<e_comp0::RegisterBlock, 0x08e0>;
impl core::fmt::Debug for EComp0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("EComp0").finish()
    }
}
#[doc = "eCOMP0"]
pub mod e_comp0;
#[no_mangle]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "P1"]
    pub p1: P1,
    #[doc = "P2"]
    pub p2: P2,
    #[doc = "P3"]
    pub p3: P3,
    #[doc = "P4"]
    pub p4: P4,
    #[doc = "P5"]
    pub p5: P5,
    #[doc = "P6"]
    pub p6: P6,
    #[doc = "SFR"]
    pub sfr: Sfr,
    #[doc = "PMM"]
    pub pmm: Pmm,
    #[doc = "SYS"]
    pub sys: Sys,
    #[doc = "CS"]
    pub cs: Cs,
    #[doc = "FRCTL"]
    pub frctl: Frctl,
    #[doc = "CRC"]
    pub crc: Crc,
    #[doc = "WDT_A"]
    pub wdt_a: WdtA,
    #[doc = "RTC"]
    pub rtc: Rtc,
    #[doc = "PJ"]
    pub pj: Pj,
    #[doc = "TA0"]
    pub ta0: Ta0,
    #[doc = "TA1"]
    pub ta1: Ta1,
    #[doc = "TA2"]
    pub ta2: Ta2,
    #[doc = "TA3"]
    pub ta3: Ta3,
    #[doc = "TB0"]
    pub tb0: Tb0,
    #[doc = "MPY32"]
    pub mpy32: Mpy32,
    #[doc = "E_USCI_A0"]
    pub e_usci_a0: EUsciA0,
    #[doc = "E_USCI_A1"]
    pub e_usci_a1: EUsciA1,
    #[doc = "E_USCI_B0"]
    pub e_usci_b0: EUsciB0,
    #[doc = "E_USCI_B1"]
    pub e_usci_b1: EUsciB1,
    #[doc = "BKMEM"]
    pub bkmem: Bkmem,
    #[doc = "ADC"]
    pub adc: Adc,
    #[doc = "E_COMP0"]
    pub e_comp0: EComp0,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        DEVICE_PERIPHERALS = true;
        Peripherals {
            p1: P1::steal(),
            p2: P2::steal(),
            p3: P3::steal(),
            p4: P4::steal(),
            p5: P5::steal(),
            p6: P6::steal(),
            sfr: Sfr::steal(),
            pmm: Pmm::steal(),
            sys: Sys::steal(),
            cs: Cs::steal(),
            frctl: Frctl::steal(),
            crc: Crc::steal(),
            wdt_a: WdtA::steal(),
            rtc: Rtc::steal(),
            pj: Pj::steal(),
            ta0: Ta0::steal(),
            ta1: Ta1::steal(),
            ta2: Ta2::steal(),
            ta3: Ta3::steal(),
            tb0: Tb0::steal(),
            mpy32: Mpy32::steal(),
            e_usci_a0: EUsciA0::steal(),
            e_usci_a1: EUsciA1::steal(),
            e_usci_b0: EUsciB0::steal(),
            e_usci_b1: EUsciB1::steal(),
            bkmem: Bkmem::steal(),
            adc: Adc::steal(),
            e_comp0: EComp0::steal(),
        }
    }
}
